### ISSUE TITLE
Зачем тут конструкция [...something]?

### ISSUE THREAD

**Issue by Bolmazov** [ValeryStatinov/FrontEnd#1]
https://github.com/ValeryStatinov/FrontEnd/blob/74867f0c228995d4ba26b30e7ab4936d97930408/AmazingTable/src/AmazingTable.js#L51

**Comment by Bolmazov** [comment]
> tableData в локальном стейте будет ссылаться на тот же участок памяти
Да, будут. Но это в этом нет ни чего страшного если не допускать мутации данных.
При сортировке ты как раз избавляешься от мутации 
`let sortedTableData = [...this.state.tableData];`
Так что в сторейдже ни чего не изменится.

**Comment by ValeryStatinov** [comment]
а да, точно. тогда это излишнее копирование данных, можно без квадратных скобок
