### ISSUE TITLE
Почему let?

### ISSUE THREAD

**Issue by Bolmazov** [ValeryStatinov/FrontEnd#2]
https://github.com/ValeryStatinov/FrontEnd/blob/74867f0c228995d4ba26b30e7ab4936d97930408/AmazingTable/src/AmazingTable.js#L87

**Comment by Bolmazov** [comment]
Что на счёт const? Что тут лучше let или const? Почему?
чт, 18 окт. 2018 г. в 13:27, Valery Statinov <notifications@github.com>:

**Comment by ValeryStatinov** [comment]
```const``` и ```let``` будут вести себя одинаково, за исключением того, что ```const```'у нельзя будет присвоить другое значение или объект(поля объекта при этом изменять можно). Поэтому, наверное, лучше использовать ```const``` чтобы объект ТОЧНО содержал в себе поля(никто случайно не записал в tableProps объект с другими полями или что-то еще), необходимые для компонента ```Table``` в качестве пропсов
