### ISSUE TITLE
Как сверстать это правильно?

### ISSUE THREAD

**Issue by Bolmazov** [ValeryStatinov/FrontEnd#3]
https://github.com/ValeryStatinov/FrontEnd/blob/74867f0c228995d4ba26b30e7ab4936d97930408/AmazingTable/src/AmazingTable.js#L103

**Comment by ValeryStatinov** [comment]
Не понимаю немного вопроса. Мне кажется это нормальным решением.

**Comment by Bolmazov** [comment]
Как реализовать это толь на css?
чт, 18 окт. 2018 г. в 13:28, Valery Statinov <notifications@github.com>:

**Comment by ValeryStatinov** [comment]
Чтобы реализовать только на CSS нужно использовать ```tr:nth-child(even)``` or odd селектор. Честно говоря не знал о таком:)
