### ISSUE TITLE
Где более правильным было бы реализовать эту ЛОГИКУ?

### ISSUE THREAD

**Issue by Bolmazov** [ValeryStatinov/FrontEnd#4]
https://github.com/ValeryStatinov/FrontEnd/blob/74867f0c228995d4ba26b30e7ab4936d97930408/AmazingTable/src/AmazingTable.js#L9

**Comment by ValeryStatinov** [comment]
Правильнее было бы реализовать эту логику в TableWrapper и передавать в Table уже значение хедера.
