### ISSUE TITLE
Как ты выбирал какие Actions должны быть в приложении? Почему в нём только одно действие? Почему именно это?

### ISSUE THREAD

**Issue by Bolmazov** [ValeryStatinov/FrontEnd#5]
https://github.com/ValeryStatinov/FrontEnd/blob/74867f0c228995d4ba26b30e7ab4936d97930408/AmazingTable/src/Actions.js#L1

**Comment by ValeryStatinov** [comment]
Я считал что в actions должны войти действия, связанные с изменением сторейджа редакса или для связи с внешним миром. В данном случае загрузить данные таблицы с серва есть связь с внешним миром, поэтому такая функция появилась в actions.
Почему, например, сортировка таблицы не вынесена в actions? Потому что в этот момент таблица работает со своим локальным стейтом, => необходимости в отдельном экшене нет, ни другим компонентам, ни сторейджу об этом знать не нужно. Если бы появилось событие, триггером для которого являлась бы сортировка таблицы, то после сортировки(все еще проводимой в рамках компонента таблицы) выстреливался бы соотвествующий экшн, чтобы запустить событие.
